import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        paddingHorizontal: 10,
        paddingVertical: 24,
    },
    background: {
        position: 'absolute',
        left: 0,
        right: 0,
        top: 0,
        height: '100%',
    },
    carteira: {
        height: 120,
        backgroundColor: '#b5ddda',
        borderRadius: 20,
        paddingTop: 13,
        paddingHorizontal: 10,
        textAlign: 'left',
    },
    reais: {
        height: 77,
        marginHorizontal: 61,
        color: '#000',
        backgroundColor: '#EBE789',
        marginBottom: 0,
        borderTopStartRadius: 25,
        borderTopEndRadius: 25,
        justifyContent: 'space-around',
        alignItems: 'center',
    },
    despesas: {
        height: 40,
        backgroundColor: '#EBE789',
        width: '50%',
        borderTopStartRadius: 15,
        borderBottomLeftRadius: 15,
        alignItems: 'center',
        justifyContent: 'center',
        color: '#000'
    },
    renda: {
        height: 40,
        backgroundColor: '#48472A',
        width: '50%',
        borderBottomEndRadius: 15,
        borderTopEndRadius: 15,
        alignItems: 'center',
        justifyContent: 'center',
        color: '#000'
    },
    opcoes: {
        marginVertical: 21,  
    },
    diaMes: {
        height: 50,
        borderRadius: 37,
        backgroundColor: '#6D7574',
        alignItems: 'center',
        justifyContent: 'center',
    },
    gastos: {
        height: 390,
        backgroundColor: '#383838',
        borderRadius: 25,
        padding: 20,
    },
    dia: {
        height: 30,
        width: '20%',
        backgroundColor: '#EBE789',
        alignItems: 'center',
        justifyContent: 'center',
        borderTopStartRadius: 10,
        borderBottomLeftRadius: 10,
    },
    semana: {
        height: 30,
        width: '20%',
        backgroundColor: '#48472A',
        alignItems: 'center',
        justifyContent: 'center',
    },
    mes: {
        height: 30,
        width: '20%',
        backgroundColor: '#48472A',
        alignItems: 'center',
        justifyContent: 'center',
    },
    ano: {
        height: 30,
        width: '20%',
        backgroundColor: '#48472A',
        alignItems: 'center',
        justifyContent: 'center',
    },
    periodo: {
        height: 30,
        width: '20%',
        backgroundColor: '#48472A',
        alignItems: 'center',
        justifyContent: 'center',
        borderBottomEndRadius: 10,
        borderTopEndRadius: 10,
    },
    eclipse: {
        width: 205,
        height: 205,
        borderRadius: '100%',
        backgroundColor: '#67ADAD',
        margin: 70,
        alignItems: 'center',
        justifyContent: 'center',
    },
    eclipse2: {
        width: 156,
        height: 156,
        borderRadius: '100%',
        backgroundColor: '#B4E4E4',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 30,
    },
});